import PDFDocument from 'pdfkit';
import type {
  ReportEquipmentSummary,
  ReportInspectionDetail,
  ReportFilters,
  ReportExportOptions,
} from '@mat-inspect/shared-schemas';
import type { ChainSegmentForReport } from './chain-segment.js';
import { fetchPhoto } from './blob-storage.js';

export type BuildReportPdfParams = {
  equipment: ReportEquipmentSummary[];
  inspections: ReportInspectionDetail[];
  filters: ReportFilters;
  chainSegment: ChainSegmentForReport;
  options: ReportExportOptions;
  generatedBy: string;
};

const digestLine = (matches: boolean | null): string => {
  if (matches === null)
    return 'No audit event found for this inspection (delivery pending or missing)';
  return matches
    ? 'PASS - matches the digest sealed in the audit chain'
    : 'MISMATCH - stored data does not match the digest sealed in the audit chain';
};

// PDFKit builder (ARCHITECTURE.md roadmap commits to PDFKit; ADR 0022 explains why signing is
// detached rather than an embedded PAdES signature that would need a different library). Kept
// synchronous-document-structure/async-photo-fetch: PDFKit's own API is synchronous per call, so
// photo bytes are awaited before each doc.image() rather than streamed concurrently, keeping page
// order deterministic.
export const buildInspectionsPdf = async (params: BuildReportPdfParams): Promise<Buffer> => {
  const doc = new PDFDocument({ margin: 50 });
  const chunks: Buffer[] = [];
  doc.on('data', (chunk: Buffer) => chunks.push(chunk));
  const finished = new Promise<Buffer>((resolve) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)));
  });

  const equipmentById = new Map(params.equipment.map((row) => [row.id, row]));
  const digestByInspectionId = new Map(
    params.chainSegment.digestChecks.map((check) => [check.inspectionId, check]),
  );

  doc.fontSize(18).text('MAT-Inspect Audit Report', { align: 'center' });
  doc.moveDown();
  doc
    .fontSize(10)
    .text(`Date range: ${params.filters.dateFrom} to ${params.filters.dateTo}`)
    .text(
      `Equipment: ${params.equipment.map((row) => `${row.assetTag} (${row.name})`).join(', ') || 'none matched'}`,
    )
    .text(`Generated: ${new Date().toISOString()}`)
    .text(`Generated by: ${params.generatedBy}`);

  if (params.inspections.length === 0) {
    doc.moveDown();
    doc.fontSize(12).text('No inspections matched the given equipment and date range.');
  }

  for (const inspection of params.inspections) {
    const equipmentRow = equipmentById.get(inspection.equipmentId);
    const digest = digestByInspectionId.get(inspection.id);

    doc.addPage();
    doc.fontSize(14).text(`Inspection ${inspection.id}`);
    doc
      .fontSize(10)
      .text(
        `Equipment: ${equipmentRow?.assetTag ?? inspection.equipmentId} - ${equipmentRow?.name ?? ''}`,
      )
      .text(`Operator: ${inspection.operatorDisplayName}`)
      .text(`Submitted: ${inspection.submittedAt}`)
      .text(`Result: ${inspection.result}`)
      .text(
        'Attestation: operator identity from the validated token, confirmed after reviewing a ' +
          'summary of their answers, server timestamp (ADR 0007). No signature column by design.',
      );

    doc.moveDown();
    doc.fontSize(11).text('Content-digest verification (ADR 0008):');
    doc.fontSize(10).text(digest === undefined ? 'Not checked' : digestLine(digest.digestMatches));

    doc.moveDown();
    doc.fontSize(11).text('Responses:');
    for (const response of inspection.responses) {
      const isVoice =
        response.notesSource === 'VOICE_TRANSCRIBED' || response.notesSource === 'VOICE_EDITED';
      const notesLine =
        response.notes && params.options.includeVoiceTranscripts
          ? ` | Notes${isVoice ? ' (from voice)' : ''}: ${response.notes}`
          : '';
      doc
        .fontSize(9)
        .text(`- ${response.prompt}: ${response.passed ? 'PASS' : 'FAIL'}${notesLine}`);

      // photoIds is always [] until DEV-104 wires per-response photo evidence through; this loop
      // is already correct for when it does, with no second audit-side change needed.
      if (params.options.includePhotos) {
        for (const photoId of response.photoIds) {
          const photo = await fetchPhoto(photoId);
          if (!photo) {
            doc.fontSize(8).text(`  (photo ${photoId} unavailable)`);
            continue;
          }
          try {
            doc.image(photo, { fit: [300, 300] });
          } catch {
            doc.fontSize(8).text(`  (photo ${photoId} could not be rendered)`);
          }
        }
      }
    }

    if (inspection.defects.length > 0) {
      doc.moveDown();
      doc.fontSize(11).text('Defects:');
      for (const defect of inspection.defects) {
        doc
          .fontSize(9)
          .text(`- [${defect.severity}] ${defect.description} (status: ${defect.status})`);

        if (params.options.includePhotos) {
          for (const photoId of defect.photoIds) {
            const photo = await fetchPhoto(photoId);
            if (!photo) {
              doc.fontSize(8).text(`  (photo ${photoId} unavailable)`);
              continue;
            }
            try {
              doc.image(photo, { fit: [300, 300] });
            } catch {
              doc.fontSize(8).text(`  (photo ${photoId} could not be rendered)`);
            }
          }
        }
      }
    }
  }

  if (params.options.includeAuditChainSegment) {
    doc.addPage();
    doc.fontSize(14).text('Audit chain segment');
    doc
      .fontSize(10)
      .text(
        params.chainSegment.chainOk
          ? `Verified intact: ${params.chainSegment.chainCheckedCount} events checked, genesis ` +
              'through the newest event relevant to this export.'
          : `CHAIN BROKEN at seq ${params.chainSegment.chainBrokenAtSeq}. This export's tamper-` +
              'evidence cannot be relied on; escalate before treating it as authoritative.',
      );
    doc.moveDown();
    for (const event of params.chainSegment.segment) {
      doc
        .fontSize(7)
        .text(
          `seq ${event.seq} | ${event.action} | ${event.resourceType}:${event.resourceId} | ` +
            `${event.occurredAt.toISOString()} | prev=${event.prevHash.slice(0, 12)}... ` +
            `this=${event.thisHash.slice(0, 12)}...`,
        );
    }
  }

  doc.addPage();
  doc
    .fontSize(9)
    .text(
      'This file has no embedded PDF signature (ADR 0022). Its SHA-256 and a detached RSA ' +
        'signature over that hash are recorded on the export job and returned by ' +
        "GET /api/v1/reports/:jobId. Verify by recomputing this file's SHA-256 and checking the " +
        'signature against the published signing key fingerprint.',
    );

  doc.end();
  return finished;
};
